apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-msa-member-depl
  namespace: js-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-msa-member
  template:
    metadata:
      labels:
        app: js-msa-member
    spec:
      containers:
      - name: js-msa-member
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/js-msa-member:latest
        ports:
        - containerPort: 8080
        env: 
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: js-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: js-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: js-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: js-app-secrets
              key: AWS_SECRET
        
---
apiVersion: v1
kind: Service
metadata:
  name: js-msa-member-service
  namespace: js-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: js-msa-member