apiVersion: v1
kind: Pod
metadata:
  name: js-nginx
  namespace: js-ns
  #labels는 service의 라우팅 대상이 되는 이름
  #service의 selector.app을 통해 매핑
  
  labels:
    app: js-nginx
spec:
  containers:
  - name: js-nginx
    image: nginx
    ports:
    - containerPort: 80